"""change schedule start time to time

Revision ID: c4bb9175aa62
Revises: e2b307048b05
Create Date: 2026-10-05 16:59:21.577506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bb9175aa62'
down_revision: Union[str, Sequence[str], None] = 'e2b307048b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedules",
        "start_time",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.Time(),
        existing_nullable=True,
        postgresql_using="start_time::time without time zone",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedules",
        "start_time",
        existing_type=sa.Time(),
        type_=sa.VARCHAR(length=5),
        existing_nullable=True,
        postgresql_using="to_char(start_time, 'HH24:MI')",
    )
    # ### end Alembic commands ###
